#!/usr/bin/env python

# generates tab-separated successive pairs from stdin
# e.g:
# >>> seq 3 | successive
# 1 2
# 2 3
# example usecase:
# ls /tmp/richard_67_dpap/01/*.png | successive | parallel --colsep '\t' ./gms_match_demo {1} {2} /tmp/gmstest/{1/}

import sys
import fileinput

prev = None
for line in fileinput.input():
    line = line.strip()
    if prev is not None:
        sys.stdout.write(prev + "\t" + line + "\n")
    prev = line
